<?php

namespace Database\Seeders;

use App\Models\Event;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class EventSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $ListEvents = [
            [
                'name' => 'Technology Summit ',
                'description' => 'A gathering of industry leaders and experts to discuss the latest trends and innovations in technology.',
                'date' => '2023-11-12',
                'time' => '6:00:00',
                'location' => 'Order MeanChey',
                'image' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSfMr2yKh_BlLSyTTSkc0EyRzbR9P6wkzo-kw&usqp=CAU',
                'venue' => "At Berng snuor",
                'organizer_id' => 4,
                'category_id' => 1,
                'is_public' => 1,
                'latitude' => 11.570633,
                'longitude' => 104.927112,

            ],
            [
                'name' => 'Career Fair',
                'description' => 'An event where companies and organizations meet with job seekers to discuss potential employment opportunities.',
                'date' => '2023-12-12',
                'time' => '9:00:00',
                'location' => 'Banteay Meanchey',
                'image' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSwpqZRImsfypEDxVhFKf3HV3lbJzHoGf2tLKf6pz9YwcLi5Bp1IXpxhan4NwhER7p2Y3k&usqp=CAU',
                'venue' => "At Banteay Meanchey",
                'organizer_id' => 3,
                'category_id' => 4,
                'is_public' => 1,
                'latitude' => 11.563804,
                'longitude' => 104.930285,

            ],
            [
                'name' => 'Business Conference',
                'description' => 'A gathering of professionals from a specific industry or field to discuss and exchange ideas on relevant topics.',
                'date' => '2023-10-12',
                'time' => '4:32:00',
                'location' => 'Batambong',
                'image' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSvD3Ghk2JQ2XxCQU3fJb6jgs9Rc0pFNLdzIA&usqp=CAU',
                'venue' => "At Batambong",
                'organizer_id' => 2,
                'category_id' => 1,
                'is_public' => 1,
                'latitude' => 11.544893,
                'longitude' => 104.912683,

            ],
            [
                'name' => 'World Music Festival',
                'description' => ' Explore the rich diversity of world music with this exciting festival. Featuring a variety of international musicians and performers.',
                'date' => '2023-12-12',
                'time' => '4:32:00',
                'location' => 'Kep',
                'image' => 'https://okefmacau.hk.ufileos.com/public/1635493208303.jpg',
                'venue' => "On the beach",
                'organizer_id' => 4,
                'category_id' => 3,
                'is_public' => 1,
                'latitude' => 11.484967,
                'longitude' => 104.877136,

            ],
            [
                'name' => 'Electric Guitar Gods',
                'description' => 'Witness the mastery of electric guitar with this electrifying concert. Featuring some of the most talented guitarists in the world.',
                'date' => '2024-07-08',
                'time' => '2:30:00',
                'location' => 'Phnom Penh',
                'image' => 'https://i.ytimg.com/vi/PKEni7qaE5Y/maxresdefault.jpg',
                'venue' => "At aeon",
                'organizer_id' => 2,
                'category_id' => 2,
                'is_public' => 1

            ],
            [
                'name' => 'Concert',
                'description' => 'Hello evryone plase join this concert',
                'date' => '2023-07-08',
                'time' => '3:32:00',
                'location' => 'Phnom Penh',
                'image' => 'https://d2al04l58v9bun.cloudfront.net/blog/wp-content/uploads/2023/01/19160943/BTS-Members-And-Their-Zodiac-Signs.png',
                'venue' => "At WAT PHNOM",
                'organizer_id' => 1,
                'category_id' => 1,
                'is_public' => 1,
                'latitude' => 11.563309,
                'longitude' => 104.893327,

            ],
            [
                'name' => 'Summer Nights Music Festival',
                'description' => 'Join us for an unforgettable night of music and entertainment under the stars. Featuring top artists and bands from around the world.',
                'date' => '2023-10-08',
                'time' => '8:30:00',
                'location' => 'Phnom Penh',
                'image' => 'https://img.myloview.com/stickers/music-party-brochure-electronic-music-covers-for-summer-fest-or-club-party-flyer-colorful-waves-gradient-background-template-for-dj-poster-web-banner-pop-up-jazz-festival-700-210697834.jpg',
                'venue' => "At WAT PHNOM",
                'organizer_id' => 4,
                'category_id' => 2,
                'is_public' => 1,
                'latitude' => 11.569450,
                'longitude' => 104.890678,

            ],
            [
                'name' => 'Jazz in the Park',
                'description' => 'A weekend of smooth jazz, delicious food, and good company. Relax and unwind to the sounds of some of the best jazz musicians in the business',
                'date' => '2023-11-08',
                'time' => '6:00:00',
                'location' => 'Press Seyhanuk',
                'image' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR0fsmCkMm4PITirWCYla8X6VyPLNOLV8MBcw&usqp=CAU',
                'venue' => "At the beach",
                'organizer_id' => 2,
                'category_id' => 2,
                'is_public' => 1,
                'latitude' => 11.553375,
                'longitude' => 104.919171,

            ],
            [
                'name' => 'Workshop',
                'description' => 'At PNC has a workshop about Technology',
                'date' => '2023-08-09',
                'time' => '1:00:00',
                'location' => 'Phnom Penh',
                'image' => 'https://img.freepik.com/free-vector/gradient-business-horizontal-banner_23-2149695720.jpg',
                'venue' => "At PNC",
                'organizer_id' => 1,
                'category_id' => 2,
                'is_public' => 1,
                'latitude' => 11.567218,
                'longitude' => 104.920433,

            ],
            [
                'name' => 'Soprt',
                'description' => 'PNC students they are has football competition with EDM students',
                'date' => '2023-10-08',
                'time' => '2:30:00',
                'location' => 'Phnom Penh',
                'image' => 'https://www.konami.com/efootball/s/img/page/season2_2023/efootball2023_internationalcup-experience.jpg',
                'venue' => "At PSE",
                'organizer_id' => 2,
                'category_id' => 1,
                'is_public' => 1,
                'latitude' => 11.558720,
                'longitude' => 104.917961,

            ],
            [
                'name' => 'Country Nights',
                'description' => 'Grab your cowboy boots and head on over to this country music extravaganza. Featuring a variety of country music artists and bands.',
                'date' => '2023-11-09',
                'time' => '1:30:00',
                'location' => 'Phnom Penh',
                'image' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXy0mjsmXDDvOHq4mBVZFG2qP1kJt1zfHPWg&usqp=CAU',
                'venue' => "At Rolyal Palase",
                'organizer_id' => 2,
                'category_id' => 1,
                'is_public' => 1,
                'latitude' => 11.572915,
                'longitude' => 104.884368,

            ],
            [
                'name' => 'Art',
                'description' => 'Hello everyone do you want to join this event?',
                'date' => '2023-11-11',
                'time' => '4:00:00',
                'location' => 'Phnom Penh',
                'image' => 'https://img.freepik.com/free-vector/flat-design-leaves-art-exhibition-facebook-template_23-2149481815.jpg?w=2000',
                'venue' => "In front of the Royal Palace",
                'organizer_id' => 2,
                'category_id' => 3,
                'is_public' => 1,
                'latitude' => 11.567791,
                'longitude' => 104.890668,

            ],
            [
                'name' => 'Bussiness',
                'description' => 'It easy to create a business by your own',
                'date' => '2023-12-12',
                'time' => '11:00:00',
                'location' => 'Oder MeanChey Province',
                'image' => 'https://img.freepik.com/free-psd/digital-marketing-agency-corporate-social-media-post-square-web-banner-template_505751-3195.jpg?w=2000',
                'venue' => "At Berng Snour",
                'organizer_id' => 3,
                'category_id' => 2,
                'is_public' => 1,
                'latitude' => 11.570633,
                'longitude' => 104.927112,
            ],
            [
                'name' => 'Electric Dreams',
                'description' => ' Immerse yourself in the world of electronic music with this electrifying concert. Featuring top DJs and electronic music producers.',
                'date' => '2023-11-12',
                'time' => '10:00:00',
                'location' => 'Kompong Cham',
                'image' => 'https://flxt.tmsimg.com/assets/p14537625_b_h10_ai.jpg',
                'venue' => "At city",
                'organizer_id' => 2,
                'category_id' => 2,
                'is_public' => 1
            ],
            [
                'name' => 'Game',
                'description' => 'Join now',
                'date' => '2024-01-10',
                'time' => '9:00:00',
                'location' => 'TaKao Province',
                'image' => 'https://fiverr-res.cloudinary.com/images/q_auto,f_auto/gigs/273906027/original/5554387306b011bdffb38446806a49cb06d9c57b/create-an-awesome-esports-tournament-gaming-banner-poster-and-event-flyer-d52e.jpg',
                'venue' => "At Takao",
                'organizer_id' => 4,
                'category_id' => 2,
                'is_public' => 1,
                'latitude' => 11.575571,
                'longitude' => 104.916816,

            ],
            [
                'name' => 'IT event',
                'description' => 'For IT students',
                'date' => '2024-02-02',
                'time' => '8:00:00',
                'location' => 'Kompong Tom Province',
                'image' => 'https://img.evbuc.com/https%3A%2F%2Fcdn.evbuc.com%2Fimages%2F516654089%2F896464871673%2F1%2Foriginal.20230517-112439?w=512&auto=format%2Ccompress&q=75&sharp=10&rect=0%2C0%2C1920%2C960&s=8b79ebf9e7477bb9b7b5183123b0538b',
                'venue' => "At Kompong Tom",
                'organizer_id' => 5,
                'category_id' => 3,
                'is_public' => 1,
                'latitude' => 11.570633,
                'longitude' => 104.927112,

            ],
            [
                'name' => 'public speaking',
                'description' => 'Please join this event all together',
                'date' => '2024-03-02',
                'time' => '1:00:00',
                'location' => 'Batambong Province',
                'image' => 'https://theknowledgereview.com/wp-content/uploads/2019/01/Public-Speaking.jpg',
                'venue' => "At Batambong",
                'organizer_id' => 4,
                'category_id' => 3,
                'is_public' => 1,
                'latitude' => 11.573892,
                'longitude' => 104.911347,
            ],
            [
                'name' => 'Sing a Song',
                'description' => 'It very enjoy if you join this event',
                'date' => '2024-05-02',
                'time' => '12:00:00',
                'location' => 'kep Province',
                'image' => 'https://www.billboard.com/wp-content/uploads/2022/04/bts-permission-to-dance-las-vegas-04082022-billboard-1548.jpg',
                'venue' => "At Kep",
                'organizer_id' => 3,
                'category_id' => 2,
                'is_public' => 1,
                'latitude' => 11.563804,
                'longitude' => 104.930285,

            ],
            [
                'name' => 'Esport',
                'description' => 'Meeting with Esport in the United States for Enterprise Development.',
                'date' => '2024-07-02',
                'time' => '7:00:00',
                'location' => 'Phnom Penh',
                'image' => 'https://i.ytimg.com/vi/3oBITepA0Sc/maxresdefault.jpg',
                'venue' => "Aeon",
                'organizer_id' => 3,
                'category_id' => 6,
                'is_public' => 1,
                'latitude' => 11.570809,
                'longitude' => 104.922381,

            ],
            [
                'name' => 'Soulful Sessions',
                'description' => 'Feel the music in your soul with this unforgettable soul music concert. Featuring some of the most talented soul singers and musicians.',
                'date' => '2023-09-02',
                'time' => '7:00:00',
                'location' => 'Phnom Penh',
                'image' => 'https://www.shepherdheartconsulting.com/wp-content/uploads/2020/10/Pastor-Care-Fund.png',
                'venue' => "Aeon",
                'organizer_id' => 3,
                'category_id' => 6,
                'is_public' => 1,
                'latitude' => 11.544893,
                'longitude' => 104.912683,

            ],
            [
                'name' => 'Soulful Blues Fest',
                'description' => 'Get ready to feel the blues with this soulful and powerful concert. Featuring some of the best blues musicians in the business.',
                'date' => '2023-10-02',
                'time' => '4:00:00',
                'location' => 'kandal',
                'image' => 'https://www.northcharlestoncoliseumpac.com/assets/img/2021-Blues-Festival-Website-thumbnail-83827891a0.jpg',
                'venue' => "kandal",
                'organizer_id' => 3,
                'category_id' => 1,
                'is_public' => 1,
                'latitude' => 11.484967,
                'longitude' => 104.877136,
        

            ],
            [
                'name' => 'Gaming Convention',
                'description' => 'An event focused on video and tabletop gaming, often featuring tournaments, demos, and panel discussions.',
                'date' => '2023-9-02',
                'time' => '4:00:00',
                'location' => 'Phnom Penh',
                'image' => 'https://click-storm.com/i/articles/0/1221/bennerhearthstone3.jpg',
                'venue' => "kaoh pech",
                'organizer_id' => 2,
                'category_id' => 2,
                'is_public' => 1,
                'latitude' => 11.563309,
                'longitude' => 104.893327,

            ],
            [
                'name' => 'Rockin Blues',
                'description' => 'Let the blues wash over you with this soulful and powerful concert. Featuring some of the best blues musicians in the business.',
                'date' => '2023-12-02',
                'time' => '4:00:00',
                'location' => 'Phnom Penh',
                'image' => 'https://cdn-az.allevents.in/events5/banners/afd848ade9b3518f18c7527bc4a5776d2008d0022e76c38bb4a59910d7544992-rimg-w960-h504-gmir.jpg?v=1683323889',
                'venue' => "Olympic",
                'organizer_id' => 3,
                'category_id' => 3,
                'is_public' => 1,
                'latitude' => 11.567218,
                'longitude' => 104.920433,

            ],
            [
                'name' => 'Classical Masterpieces',
                'description' => ' Enjoy an evening of classical music with some of the most talented musicians in the world. Featuring performances of some of the greatest classical works ever written.',
                'date' => '2023-08-12',
                'time' => '5:00:00',
                'location' => 'Phnom Penh',
                'image' => 'https://i.ytimg.com/vi/l8jfCiaCZhU/maxresdefault.jpg',
                'venue' => "Olympic",
                'organizer_id' => 5,
                'category_id' => 1,
                'is_public' => 1,
                'latitude' => 11.538954,
                'longitude' => 104.910152,

            ],
            [
                'name' => 'R&B Explosion',
                'description' => 'Get ready for a night of soulful R&B music with this explosive concert. Featuring some of the biggest names in the R&B music scene.',
                'date' => '2023-07-30',
                'time' => '5:30:00',
                'location' => 'Kandal',
                'image' => 'https://www.313presents.com/assets/img/rbme-detroit-1080x1080-b0a41e1661.jpg',
                'venue' => "At kandal",
                'organizer_id' => 5,
                'category_id' => 1,
                'is_public' => 1,
                'latitude' => 11.564350,
                'longitude' => 104.934307,

            ],
            [
                'name' => 'Music Festival',
                'description' => 'A festival featuring live music performances from local and international artists.',
                'date' => '2023-08-20',
                'time' => '16:00:00',
                'location' => 'Koh Pich',
                'image' => 'https://img.pikbest.com/backgrounds/20210812/music-festival-cartoon-fun-banner_6085337.jpg!sw800',
                'venue' => "At Koh Pich Convention and Exhibition Center",
                'organizer_id' => 1,
                'category_id' => 2,
                'is_public' => 1,
                'latitude' => 11.546937,
                'longitude' => 104.899812,
            ],
            [
                'name' => 'Food Festival',
                'description' => 'A showcase of the latest food products and culinary innovations from around the world.',
                'date' => '2023-09-05',
                'time' => '10:00:00',
                'location' => 'Diamond Island',
                'image' => 'https://d1csarkz8obe9u.cloudfront.net/posterpreviews/food-festival%2Cretail%2Cevent%2C-menu-design-template-7a26f1d86ffac8f58db035ef1c2147a3_screen.jpg?ts=1687705232',
                'venue' => "At Diamond Island Convention and Exhibition Center",
                'organizer_id' => 2,
                'category_id' => 3,
                'is_public' => 1,
                'latitude' => 11.570809,
                'longitude' => 104.922381,
            ],
            [
                'name' => 'Fashion Show',
                'description' => 'A showcase of the latest fashion trends and designs from local and international designers.',
                'date' => '2023-10-15',
                'time' => '19:00:00',
                'location' => 'Sovanna Shopping Center',
                'image' => 'https://ww1.prweb.com/prfiles/2012/01/25/9137993/fashion%20show%20banner.jpg',
                'venue' => "At Sovanna Shopping Center",
                'organizer_id' => 3,
                'category_id' => 4,
                'is_public' => 1,
                'latitude' => 11.563309,
                'longitude' => 104.893327,
            ],
            [
                'name' => 'Sports Tournament',
                'description' => 'A tournament featuring various sports such as football, basketball, and volleyball.',
                'date' => '2023-07-29',
                'time' => '13:00:00',
                'location' => 'National Olympic Stadium',
                'image' => 'https://d1csarkz8obe9u.cloudfront.net/posterpreviews/poster-banner-with-basketball-tournament-design-template-b2783e294846c959672908ce424ff948_screen.jpg?ts=1645243610',
                'venue' => "At National Olympic Stadium",
                'organizer_id' => 5,
                'category_id' => 5,
                'is_public' => 1,
                'latitude' => 11.544893,
                'longitude' => 104.912683,
            ],
            [
                'name' => 'Art Exhibition',
                'description' => 'An exhibition featuring various forms of art such as paintings, sculptures, and installations.',
                'date' => '2023-12-08',
                'time' => '11:00:00',
                'location' => 'National Museum of Cambodia',
                'image' => 'https://i.pinimg.com/564x/d5/5a/1b/d55a1b889ad54c50f0a0ae21215ffbdc--african-design-darts.jpg',
                'venue' => "At National Museum of Cambodia",
                'organizer_id' => 5,
                'category_id' => 2,
                'is_public' => 1,
                'latitude' => 11.569987,
                'longitude' => 104.892275,
            ],
            [
                'name' => 'Career Fair',
                'description' => 'A fair featuring various job opportunities and career advice from local and international companies.',
                'date' => '2023-11-01',
                'time' => '9:00:00',
                'location' => 'Phnom Penh Hotel',
                'image' => 'https://www.jobstreet.co.id/id/cms/employer/wp-content/themes/jobstreet-employer/assets/vcf/pdf/Virtual_Career_Fair_Proposal_for_Hirers_1.jpg',
                'venue' => "At Phnom Penh Hotel",
                'organizer_id' => 1,
                'category_id' => 1,
                'is_public' => 1,
                'latitude' => 11.574804,
                'longitude' => 104.921898,
            ],
            [
                'name' => 'Film Festival',
                'description' => 'A festival featuring the latest films from local and international filmmakers.',
                'date' => '2023-10-25',
                'time' => '18:00:00',
                'location' => 'Major Cineplex',
                'image' => 'https://i.guim.co.uk/img/media/f71ed35864ca692aa57070802154faa6dbec92f3/0_394_6016_3611/master/6016.jpg?width=465&dpr=1&s=none',
                'venue' => "At Major Cineplex",
                'organizer_id' => 2,
                'category_id' => 2,
                'is_public' => 1,
                'latitude' => 11.567791,
                'longitude' => 104.890668,  
            ],
            [
                'name' => 'Charity Auction',
                'description' => 'An auction featuring various items donated by local and international celebrities and businesses to raise funds for charity.',
                'date' => '2023-11-05',
                'time' => '17:00:00',
                'location' => 'Raffles Hotel Le Royal',
                'image' => 'https://vintageshaving.au/wp-content/uploads/2022/08/Charity-Auction-Website-header.png',
                'venue' => "At Raffles Hotel Le Royal",
                'organizer_id' => 3,
                'category_id' => 3,
                'is_public' => 1,
                'latitude' => 11.572915,
                'longitude' => 104.884368,
            ],
            [
                'name' => 'Tech Conference',
                'description' => 'A conference featuring talks and presentations from industry experts on the latest technology trends and innovations.',
                'date' => '2023-09-15',
                'time' => '8:00:00',
                'location' => 'Sofitel Phnom Penh Phokeethra',
                'image' => 'https://nasscom.in/natc/images/banner-mob.jpg',
                'venue' => "At Sofitel Phnom Penh Phokeethra",
                'organizer_id' => 4,
                'category_id' => 4,
                'is_public' => 1,
                'latitude' => 11.558720,
                'longitude' => 104.917961,
            ],
            [
                'name' => 'Dance Competition',
                'description' => 'A competition featuring various dance styles such as ballet, contemporary, and hip hop.',
                'date' => '2023-08-27',
                'time' => '14:00:00',
                'location' => 'Chaktomuk Theater',
                'image' => 'https://i.ytimg.com/vi/bWxDTxejfVU/maxresdefault.jpg',
                'venue' => "At Chaktomuk Theater",
                'organizer_id' => 5,
                'category_id' => 5,
                'is_public' => 1,
                'latitude' => 11.562952,
                'longitude' => 104.925999,
            ],
            [
                'name' => 'Photography Exhibition',
                'description' => 'An exhibition featuring the works of local and international photographers.',
                'date' => '2023-10-10',
                'time' => '12:00:00',
                'location' => 'Bophana Center',
                'image' => 'https://ww2.kqed.org/app/uploads/sites/2/2014/08/lipps-800.jpg',
                'venue' => "At Bophana Center",
                'organizer_id' => 1,
                'category_id' => 2,
                'is_public' => 111.567218,
                'longitude' => 104.920433,
            ],
            [
                'name' => 'Health Expo',
                'description' => 'A showcase of the latest health products and services from local and international companies.',
                'date' => '2023-11-18',
                'time' => '10:00:00',
                'location' => 'Koh Pich',
                'image' => 'https://cdn.evbuc.com/images/130148261/212728133716/1/original.jpg',
                'venue' => "At Koh Pich Convention and Exhibition Center",
                'organizer_id' => 1,
                'category_id' => 1,
                'is_public' => 1,
                'latitude' => 11.553375,
                'longitude' => 104.919171,
            ],
            [
                'name' => 'Culinary Competition',
                'description' => 'A competition featuring various culinary styles such as Khmer cuisine, French cuisine, and Japanese cuisine.',
                'date' => '2023-09-22',
                'time' => '15:00:00',
                'location' => 'The Place Restaurant',
                'image' => 'https://i.ytimg.com/vi/Gah9Zc-x-PQ/maxresdefault.jpg',
                'venue' => "At The Place Restaurant",
                'organizer_id' => 2,
                'category_id' => 2,
                'is_public' => 1,
                'latitude' => 11.569450,
                'longitude' => 104.890678,
            ],
            [
                'name' => 'Startup Pitch Competition',
                'description' => 'A competition for early stage startups to pitch their business ideas to a panel of judges and potential investors.',
                'date' => '2023-10-05',
                'time' => '9:00:00',
                'location' => 'Raintree Cambodia',
                'image' => 'https://startupbasecamp.org/wp-content/uploads/2020/05/startup-basecamp-silicon-valley-innovation-lab-map-background-blog-post-01-1-1024x532.jpg',
                'venue' => "At Raintree Cambodia",
                'organizer_id' => 3,
                'category_id' => 3,
                'is_public' => 1,
                'latitude' => 11.563309,
                'longitude' => 104.893327,
            ],
            [
                'name' => 'Literature Festival',
                'description' => 'A festival featuring talks and readings from local and international authors and poets.',
                'date' => '2023-12-01',
                'time' => '11:00:00',
                'location' => 'FCC Angkor',
                'image' => 'https://im.whatshot.in/img/2021/Dec/pjimage109-1639641418.jpg?wm=1&w=1200&h=630&cc=1',
                'venue' => "At FCC Angkor",
                'organizer_id' => 4,
                'category_id' => 4,
                'is_public' => 1,
                'latitude' => 11.484967,
                'longitude' => 104.877136,
            ],
            [
                'name' => 'Environmental Exhibition',
                'description' => 'An exhibition featuring the latest environmental products and services from local and international companies.',
                'date' => '2023-11-08',
                'time' => '10:00:00',
                'location' => 'Koh Pich',
                'image' => 'https://learnenglish.britishcouncil.org/sites/podcasts/files/RS7824_ThinkstockPhotos-506316644-hig.jpg',
                'venue' => "At Koh Pich Convention and Exhibition Center",
                'organizer_id' => 5,
                'category_id' => 5,
                'is_public' => 1,
                'latitude' => 11.544893,
                'longitude' => 104.912683,
            ],
            [
                'name' => 'Art competition',
                'description' => 'An auction featuring various artworks donated by local and international artists to raise funds for charity.',
                'date' => '2023-12-03',
                'time' => '18:00:00',
                'location' => 'Sofitel Phnom Penh Phokeethra',
                'image' => 'https://mulcaircu.ie/wp-content/uploads/2019/11/06092019-161158.jpg',
                'venue' => "At Sofitel Phnom Penh Phokeethra",
                'organizer_id' => 3,
                'category_id' => 5,
                'is_public' => 1,
                'latitude' => 11.570809,
                'longitude' => 104.922381,
            ],
        ];
        foreach ($ListEvents as $ListEvent) {
            Event::create($ListEvent);
        }
    }
}
